- nodeset:
    name: devstack-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: devstack-gate-hooks
    parent: legacy-dsvm-base
    run: playbooks/devstack-gate-hooks/run.yaml
    post-run: playbooks/devstack-gate-hooks/post.yaml
    timeout: 3900

- job:
    name: legacy-tempest-neutron-full-stable
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-neutron-full/run.yaml
    post-run: playbooks/legacy/tempest-neutron-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest

- project:
    templates:
      - integrated-gate-py3
      - official-openstack-repo-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - openstack-tox-bashate:
            nodeset: ubuntu-bionic
        - openstack-tox-py27
        - neutron-grenade
        - neutron-grenade-multinode
        - neutron-grenade-dvr-multinode:
            voting: false
        - legacy-tempest-dsvm-neutron-full-ocata:
            voting: false
        - legacy-tempest-dsvm-neutron-full-centos-7:
            voting: false
        - legacy-tempest-dsvm-multinode-full:
            voting: false
        - devstack:
            files:
              - ^roles/
        - neutron-tempest-plugin-api:
            voting: false
        - legacy-tempest-neutron-full-stable:
            branches: ^(?!driverfixes/).*$
            voting: false
        - devstack-gate-hooks
    gate:
      queue: integrated
      jobs:
        - openstack-tox-py27
        - neutron-grenade
        - neutron-grenade-multinode
        - devstack-gate-hooks
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-dvr-multinode-full
        - neutron-tempest-dvr-ha-multinode-full
