- nodeset:
    name: devstack-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: devstack-gate-hooks
    parent: legacy-dsvm-base
    run: playbooks/devstack-gate-hooks/run.yaml
    post-run: playbooks/devstack-gate-hooks/post.yaml
    timeout: 3900

- job:
    name: legacy-tempest-neutron-full-stable
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-neutron-full/run.yaml
    post-run: playbooks/legacy/tempest-neutron-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/neutron
      - openstack/tempest

- project:
    check:
      jobs:
        - devstack:
            files:
              - ^roles/
        - neutron-tempest-plugin-api:
            voting: false
        - legacy-tempest-neutron-full-stable:
            branches: ^(?!driverfixes/).*$
            voting: false
        - devstack-gate-hooks
